export const PALABRAS = [
    "2024-04-05",
    
    "radiacion",
    "energia limpia",
    "termosolar",
    "fotovoltaica",
    "paneles",
    "meteorologia",
    "centrales",

    "cinetica",
    "aerogenerador",
    "transformacion",
    "subterraneo",
    "corrosion",
    "parque eolico",
    "descarbonizacion",

    "corriente",
    "presa",
    "inagotable",
    "ecosistema",
    "eficiencia",
    "regeneracion",
    "riego",

    "disponibilidad",
    "residuos",
    "extincion",
    "binario",
    "yacimientos",
    "calefaccion",
    "refrigeracion",

    "marea",
    "predecible",
    "turbina",
    "densidad",
    "oleaje",
    "atenuador",
    "rendimiento",

    "biodegradable",
    "biocombustible",
    "carbono",
    "contribucion",
    "combustion",
    "descomposicion",
    "fertilizante",

    "fermentacion",
    "emisiones",
    "refinado",
    "desarrollo rural",
    "petroleo",
    "combustible",
    "produccion",
];