export const PALABRAS = [
    "2024-04-05",
    
    "Energía solar",
    "Energía solar",
    "Energía solar",
    "Energía solar",
    "Energía solar",
    "Energía solar",
    "Energía solar",

    "Energía eólica",
    "Energía eólica",
    "Energía eólica",
    "Energía eólica",
    "Energía eólica",
    "Energía eólica",
    "Energía eólica",

    "Energía hidráulica",
    "Energía hidráulica",
    "Energía hidráulica",
    "Energía hidráulica",
    "Energía hidráulica",
    "Energía hidráulica",
    "Energía hidráulica",

    "Energía geotérmica",
    "Energía geotérmica",
    "Energía geotérmica",
    "Energía geotérmica",
    "Energía geotérmica",
    "Energía geotérmica",
    "Energía geotérmica",

    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",
    "Energía mareomotriz y undimotriz",

    "Biomasa y biogas",
    "Biomasa y biogas",
    "Biomasa y biogas",
    "Biomasa y biogas",
    "Biomasa y biogas",
    "Biomasa y biogas",
    "Biomasa y biogas",

    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
    "Bioetanol y biodiésel",
];